// app/layout.tsx
import { Toaster } from "sonner";
import "../styles/globals.css";
import AppBar from "../components/layout/AppBar";
import Footer from "../components/layout/Footer";
import LayoutWrapper from "./LayoutWrapper";

require("@solana/wallet-adapter-react-ui/styles.css");

export const metadata = {
  title: "BUILDERZ Solana dApp Scaffold",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: any) {
  return (
    <LayoutWrapper>
      <html lang="en" className="h-full">
        <body className="flex flex-col min-h-screen bg-[#0a0924]">
          <AppBar />
          <main className="flex-grow pt-20 pb-16">
            {children}
          </main>
          <Footer />
          <Toaster position="bottom-right" />
        </body>
      </html>
    </LayoutWrapper>
  );
}